<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="87047" started-at="2021-05-25T18:17:27 CAT" finished-at="2021-05-25T18:18:54 CAT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="87047" started-at="2021-05-25T18:17:27 CAT" finished-at="2021-05-25T18:18:54 CAT">
      <class name="tests.loginTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:tests.loginTest@7e07db1f]" name="setup" is-config="true" duration-ms="20307" started-at="2021-05-25T18:17:27 CAT" finished-at="2021-05-25T18:17:48 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="TestUserCanLogin()[pri:0, instance:tests.loginTest@7e07db1f]" name="TestUserCanLogin" duration-ms="64938" started-at="2021-05-25T18:17:48 CAT" finished-at="2021-05-25T18:18:53 CAT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[TestUserCanLogin Failed, please investigate]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: TestUserCanLogin Failed, please investigate
at org.testng.Assert.fail(Assert.java:99)
at actions.find.ElementExists(find.java:30)
at pages.loggedinpage.VerifyLoggedIn(loggedinpage.java:105)
at tests.loginTest.TestUserCanLogin(loginTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestUserCanLogin -->
        <test-method status="PASS" signature="MethodTearDown()[pri:0, instance:tests.loginTest@7e07db1f]" name="MethodTearDown" is-config="true" duration-ms="1128" started-at="2021-05-25T18:18:53 CAT" finished-at="2021-05-25T18:18:54 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MethodTearDown -->
      </class> <!-- tests.loginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
